bill = input("What was the total bill? $")
tip = input("What percentage tip would you like to give? 10, 12, or 15? ")
people = input("How many people to split the bill? ")
each_to_pay = print(f"Each person should pay: ${round((float(bill) * (1 + float(tip) / 100)) / int(people), 2)}")
final_amount = "{:.2f}".format(float(bill) * (1 + float(tip) / 100))
print(f"Total amount to pay: ${final_amount}")